# Generated by Django 4.1.3 on 2023-08-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country_of_origin', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('imageUrl', models.CharField(default=1, max_length=1000)),
            ],
        ),
    ]
