# Generated by Django 4.1.3 on 2023-08-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpshapi', '0002_rename_imageurl_user_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('imageUrl', models.CharField(max_length=1000)),
            ],
        ),
    ]
