# Generated by Django 4.1.3 on 2023-08-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpshapi', '0003_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
