# Generated by Django 4.1.3 on 2023-08-17 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpshapi', '0004_rename_imageurl_city_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(default='', max_length=1000)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='bpshapi.city')),
            ],
        ),
    ]
